config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles, only: %i(index show)
  namespace :admin do
    resources :articles
    resources :users, only: :index 
    resource :people, only: %i(edit update) # note singular "resource" to prevent putting IDs in the route
    get "users/dashboard", :to => 'users#dashboard', :as => :dashboard
    get '*path', :to => 'users#dashboard'
  end
  resources :users, only: %i(new create)
  get "get_presigned_url", :to => 'uploads#get_presigned_url'

  # Password resets
  get "password_reset", :to => "sessions#password_reset"
  post "send_password_reset", :to => 'users#send_password_reset'

  resources :people, only: :show
  scope :users do
    get "login", :to => 'sessions#new'
    post "login", :to => 'sessions#create'
    delete "logout", :to => 'sessions#destroy'
  end

  get '*path', :to => 'application#error', :as => :error
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :author, class_name: "Person"

  before_save :set_slug, :if => Proc.new{ self.title_changed? }

  def to_param
    "#{self.id}-#{self.slug}"
  end

  def set_slug
    self.slug = self.title.parameterize(separator: "-")
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  include Paginatable
  include ActionView::Helpers::SanitizeHelper

  def index
    set_up_pagination(Article)
    @articles = @articles.order("created_at DESC")
  end

  def create
    @article = Article.new(permitted_params)
    @article.author = current_user.person
    if @article.save
      redirect_to admin_articles_path
    else
      flash[:errors] = "Article could not be created, #{@article.errors&.full_messages}"
      render :new, status: 400
    end
  end

  def destroy
    @article = Article.find(params[:id].to_i)
    unless @article
      render :error, status: 404 and return
    end
    if @article.destroy
      redirect_to admin_articles_path
      # TODO: Notify user that deleted successfully
    else
      flash[:errors] = "Article could not be dstroyed, #{@article.errors&.full_messages}"
      redirect_to admin_articles_path
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id].to_i)
    unless @article
      render :error, status: 404 and return
    end
  end

  def update
    @article = Article.find(params[:id].to_i)
    unless @article
      render :error, status: 404 and return
    end
    if @article.update(permitted_params)
      redirect_to admin_articles_path
    else
      flash[:errors] = "Article could not be updated, #{@article.errors&.full_messages}"
      render :edit, status: 400
    end
  end

  private

  def permitted_params
    params.require(:article).permit([:title, :body]).tap{|p| p[:body] = sanitize(p[:body])}
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Paginatable

  def index
    set_up_pagination(Article)
    @articles = @articles.order("created_at DESC")
  end

  def show
    @article = Article.find_by(id: params[:id].to_i)
    unless @article
      render :error, status: 404 and return
    end
    # To handle "old" slugs after a title has changed, redirect any URL requested which contains a "-" to the latest canonical URL
    if params[:id].include?("-") && !article_path(@article).include?(params[:id])
      redirect_to article_path(@article)
    end
  end

end

app/views/admin/articles/edit.html.erb
<h1>Edit your article</h1>

<%= form_with model: @article, url: admin_article_path(@article) do |form| %>
  <div class="form-fields">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="form-fields">
    <%= form.label :body %>
    <%= form.text_area :body, :class => "tinymce" %>
  </div>
  <%= form.submit "Save" %>
<% end %>

<%= link_to "See All Articles", admin_articles_path %>

app/views/admin/articles/index.html.erb
<h1>Extra! Extra! Read all about it!</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Last Updated</th>
    <th>View Live</th>
  </tr>
  <% @articles.each do |a| %>
    <tr>
      <td><%= a.id %></td>
      <td><%= link_to(a.title, edit_admin_article_path(a)) %></td>
      <td><%= a.updated_at.to_date %></td>
      <td><%= link_to("View Live", article_path(a)) %></td>
    </tr>
  <% end %>
  
</table>

<%= render 'pagination', locals: {path_prefix: "admin_articles", item: "article"} %>

<%= link_to "Create New Article!", new_admin_article_path %>

<%= link_to "Edit My Profile", edit_admin_people_path(current_user.person.id) %>
<%= link_to "View My Profile", person_path(current_user.person.id) %>

app/views/admin/articles/new.html.erb
<h1>Create your article</h1>
<%= form_with model: @article, url: admin_articles_path do |form| %>
  <div class="form-fields">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="form-fields">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.submit "Save" %>
<% end %>
<%= link_to "Back to Menu", admin_articles_path %>