config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles, only: %i(index show)
  namespace :admin do
    resources :articles
    resources :users, only: :index 
    resource :people, only: %i(edit update) # note singular "resource" to prevent putting IDs in the route
    get "users/dashboard", :to => 'users#dashboard', :as => :dashboard
    get '*path', :to => 'users#dashboard'
  end
  resources :users, only: %i(new create)
  get "get_presigned_url", :to => 'uploads#get_presigned_url'

  # Password resets
  get "password_reset", :to => "sessions#password_reset"
  post "send_password_reset", :to => 'users#send_password_reset'

  resources :people, only: :show
  scope :users do
    get "login", :to => 'sessions#new'
    post "login", :to => 'sessions#create'
    delete "logout", :to => 'sessions#destroy'
  end

  get '*path', :to => 'application#error', :as => :error
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user

  def private_name
    self.given_name.presence || "Friend"
  end

  def public_name
    self.display_name.presence || "Anonymous"
  end

  def has_social?
    [self.li_name, self.ig_name, self.fb_name, self.tw_name].any?(&:present?)
  end
end

app/controllers/admin/people_controller.rb
module Admin
  class PeopleController < ApplicationController
    def edit
      if current_user
        @person = Person.find_by(id: current_user.person&.id)
        unless @person
          render :error, status: 404 and return
        end
      else
        flash[:errors] = "You are not authorized to view this page"
        redirect_to admin_dashboard_path
      end
    end

    def update
      if current_user
        @person = Person.find_by(id: current_user.person&.id)
        unless @person
          render :error, status: 404 and return
        end
        if @person.update(permitted_params)
          redirect_to admin_dashboard_path
        else
          flash[:errors] = "People could not be updated, #{@person.errors&.full_messages}"
          render :edit, status: 400
        end
      else
        flash[:errors] = "You are not authorized to view this page"
        redirect_to admin_dashboard_path
      end
    end

    def permitted_params
      params.require(:person).permit(:name, :given_name, :display_name, :date_of_birth, :country, :city, :fb_name, :li_name, :tw_name, :ig_name,
      :bio, :slogan, :gender)
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = Person.find_by(id: params[:id].to_i)
    unless @person
      render :error, status: 404 and return
    end
  end
end

app/views/admin/people/edit.html.erb
<h2>Edit Your Profile, <%= @person.private_name %></h2>

<%= form_with model: @person, url: admin_people_path do |form| %>
  <div class="form-fields">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="form-fields">
    <%= form.label :display_name %>
    <%= form.text_field :display_name %>
  </div>
  <div class="form-fields">
    <%= form.label :given_name %>
    <%= form.text_field :given_name %>
  </div>
  <div class="form-fields">
    <%= form.label :slogan %>
    <%= form.text_field :slogan %>
  </div>
  <div class="form-fields">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>
  <div class="form-fields">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth%>
  </div>
  <div class="form-fields">
    <%= form.label :fb_name %>
    <%= form.text_field :fb_name %>
  </div>
  <div class="form-fields">
    <%= form.label :ig_name %>
    <%= form.text_field :ig_name %>
  </div>
  <div class="form-fields">
    <%= form.label :tw_name %>
    <%= form.text_field :tw_name %>
  </div>
  <div class="form-fields">
    <%= form.label :li_name %>
    <%= form.text_field :li_name %>
  </div>
  <div class="form-fields">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>
  <div class="form-fields">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>
  <div class="form-fields">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  <%= form.submit "Save" %>
<% end %>

<% if flash[:errors].present? %>
  <p><%= flash[:errors] %></p>
<% end %>